### ISSUE TITLE
Symbol’s value as variable is void: eshell-info-banner-path-separator

### ISSUE THREAD

**Issue by gopar** [Phundrak/eshell-info-banner.el#20]
Updated package today and got this. Probably due to the `eval-when-compile`. 
If I install package, error doens't exist. 
If I re-start emacs, then I encounter the error.

**Comment by Phundrak** [comment]
Hello,

This is weird, I do not have this issue on my end. I’ll remove the
`eval-when-compile` part for now.

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs
