### ISSUE TITLE
Add ZFS support

### ISSUE THREAD

**Issue by juergenhoetzel** [Phundrak/eshell-info-banner.el#9]
ATM ZFS partitions are filtered out because of the missing "/dev" prefix:
```
....
zroot/ROOT/default           1,2T    747G  458G   63% /
zroot/data/home              900G    443G  458G   50% /home
...
```

**Comment by Phundrak** [comment]
Hello! I was actually working on a solution for this! This commit should be soon closed automatically by an upcoming commit.
